services:
  postgres:
    image: postgres:16
    container_: db-postgres
    environment:
      POSTGRES_DB: mybee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: